version: "3"
services:
  redis:
    image: redis/redis-stack-server
    restart: always
    volumes:
      - ./redis/data/:/data
    environment:
      REDIS_ARGS: "--save 60 1000 --appendonly yes"
      REDIS_ARGS: "--requirepass MCKNF5_aEjgHfV9M"

  wvp:
    build:
      context: ./wvp
      args:
        gitUrl: "https://github.com/648540858" # "https://gitee.com/pan648540858"
        zlmGitUrl: "https://github.com/ZLMediaKit/ZLMediaKit.git" # "https://github.com/ZLMediaKit/ZLMediaKit"
    restart: always
    ports:
      - "5060:5060"
      - "5060:5060/udp"
      - "18080:18080"
      - "80:80"
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "30000-30500:30000-30500/tcp"
      - "30000-30500:30000-30500/udp"
    volumes:
      - ./video:/opt/media/www/record/
      - ./logs/wvp:/opt/wvp/logs/
      - ./logs/assist:/opt/assist/logs/
      - ./logs/media:/opt/media/log/
    environment:
      TZ: "$(cat /etc/timezone)"
      # [必须修改] 本机的IP
      WVP_HOST: 172.18.0.61
      WVP_PWD: aseqw_+hiy123
      WVP_DOMAIN: 6101130049
      WVP_ID: 61011300490000000001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 6
      REDIS_PWD: MCKNF5_aEjgHfV9M
      ASSIST_JVM_CONFIG: -Xms128m -Xmx256m
      WVP_JVM_CONFIG: -Xms128m -Xmx256m
      ASSIST_CONFIG:
      WVP_CONFIG:
    depends_on:
      - redis

networks:
  wvp_net:
